name: Build Instantiate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_php:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/old-home/php
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer packages
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Build Project
        run: composer build
